/**
 * E(F_{p^k}) as an exact finite abelian group with its Galois structure
 * (DESIGN.md §5.1). Points are integer pairs (x, y) mod N meaning
 * (x + yτ)/N ∈ ℂ/Λ: E(F_{p^k}) = ker(Mᵏ − I) acting on (ℚ/ℤ)², computed
 * exactly by Smith normal form. BigInt lives in the algebra; stored
 * coordinates are plain numbers, guarded < 2⁵³ at construction.
 */
import { Complex, gcd } from '@/math/core'

import { type CurveData, frobeniusMatrix, tauOf } from './curve'
import { Mat2Z } from './mat2z'

/** Exact integers mod N, meaning (x + yτ)/N ∈ ℂ/Λ. */
export interface TorusPoint {
  x: number
  y: number
}

const MAX_SAFE = 2n ** 53n

function toSafeNumber(v: bigint, what: string): number {
  if (v >= MAX_SAFE) throw new RangeError(`${what} = ${v} exceeds 2^53; not representable exactly`)
  return Number(v)
}

/**
 * E(F_{p^k}) = ker(Mᵏ − I) ⊂ (ℚ/ℤ)², exact.
 *
 * With U·(Mᵏ − I)·V = diag(d₁, d₂) (Smith form, d₁ | d₂), the kernel is
 * generated by the columns of V scaled by 1/dᵢ: (Mᵏ−I)·V·diag(1/d₁, 1/d₂)
 * = U⁻¹ is integral, and V ∈ GL₂(ℤ) makes them independent of orders d₁, d₂.
 * One denominator N = d₂ serves every point.
 */
export function pointsOver(data: CurveData, k: number): CurvePoints {
  if (!Number.isInteger(k) || k < 1) throw new RangeError(`k must be a positive integer, got ${k}`)
  const M = frobeniusMatrix(data)
  const Mk = M.pow(k).sub(Mat2Z.ID)
  const { d, V } = Mk.smithNormalForm()
  const [d1, d2] = d
  if (d2 === 0n) throw new Error(`Mᵏ − I is singular (k = ${k}): not a finite group`)
  toSafeNumber(d1 * d2, 'group order')
  const gens: TorusPoint[] = []
  // generator i = (column i of V)/dᵢ = (N/dᵢ)·colᵢ at denominator N = d₂
  for (const [di, col] of [
    [d1, [V.a, V.c]],
    [d2, [V.b, V.d]],
  ] as [bigint, [bigint, bigint]][]) {
    if (di === 1n) continue
    const s = d2 / di
    gens.push({
      x: toSafeNumber(((col[0] * s) % d2 + d2) % d2, 'coordinate'),
      y: toSafeNumber(((col[1] * s) % d2 + d2) % d2, 'coordinate'),
    })
  }
  return new CurvePoints(k, [toSafeNumber(d1, 'n1'), toSafeNumber(d2, 'n2')], gens, M, tauOf(data.form))
}

/** E(F_{p^k}) as an exact group with its Galois (Frobenius) structure. */
export class CurvePoints {
  /** Group order n₁·n₂ = pᵏ + 1 − aₖ. */
  readonly size: number
  /** ONE denominator for all points: N = n₂. */
  readonly N: number
  /** The point at infinity, (0, 0). */
  readonly identity: TorusPoint = { x: 0, y: 0 }
  /** Frobenius matrix reduced mod N. */
  private readonly frobMod: [bigint, bigint, bigint, bigint]
  private readonly bigN: bigint
  private readonly degreeCache = new Map<string, number>()

  constructor(
    readonly k: number,
    /** ℤ/n₁ × ℤ/n₂ with n₁ | n₂. */
    readonly structure: [n1: number, n2: number],
    /** 0, 1, or 2 generators, of orders n₁ ≤ n₂ (trivial factors omitted). */
    readonly generators: TorusPoint[],
    frobenius: Mat2Z,
    /** τ of the underlying form; used only by toComplex. */
    private readonly tau: Complex,
  ) {
    this.size = structure[0] * structure[1]
    this.N = structure[1]
    this.bigN = BigInt(this.N)
    const n = this.bigN
    const r = (v: bigint) => ((v % n) + n) % n
    this.frobMod = [r(frobenius.a), r(frobenius.b), r(frobenius.c), r(frobenius.d)]
  }

  add(P: TorusPoint, Q: TorusPoint): TorusPoint {
    const n = this.bigN
    return {
      x: Number((BigInt(P.x) + BigInt(Q.x)) % n),
      y: Number((BigInt(P.y) + BigInt(Q.y)) % n),
    }
  }

  neg(P: TorusPoint): TorusPoint {
    return { x: P.x === 0 ? 0 : this.N - P.x, y: P.y === 0 ? 0 : this.N - P.y }
  }

  mul(m: number, P: TorusPoint): TorusPoint {
    if (!Number.isInteger(m)) throw new RangeError(`mul: m must be an integer, got ${m}`)
    const n = this.bigN
    const mm = ((BigInt(m) % n) + n) % n
    return {
      x: Number((BigInt(P.x) * mm) % n),
      y: Number((BigInt(P.y) * mm) % n),
    }
  }

  /** Order of P in the group: N / gcd(x, y, N). */
  order(P: TorusPoint): number {
    return Number(this.bigN / gcd(gcd(BigInt(P.x), BigInt(P.y)), this.bigN))
  }

  /** Galois action: M·P mod N. */
  frobenius(P: TorusPoint): TorusPoint {
    const n = this.bigN
    const [a, b, c, d] = this.frobMod
    const x = BigInt(P.x)
    const y = BigInt(P.y)
    return { x: Number((a * x + b * y) % n), y: Number((c * x + d * y) % n) }
  }

  /**
   * Field of definition: min j (dividing k) with P ∈ E(F_{p^j}),
   * = the size of P's Frobenius orbit. Cached.
   */
  degree(P: TorusPoint): number {
    const key = `${P.x},${P.y}`
    const cached = this.degreeCache.get(key)
    if (cached !== undefined) return cached
    let Q = this.frobenius(P)
    let j = 1
    while (Q.x !== P.x || Q.y !== P.y) {
      Q = this.frobenius(Q)
      j++
      if (j > this.k) throw new Error('Frobenius orbit exceeded k — point not fixed by Mᵏ?')
    }
    this.degreeCache.set(key, j)
    return j
  }

  /**
   * The Frobenius orbits, one entry per orbit, each listing its points in
   * cyclic M-order (P, MP, M²P, …). Orbit size = degree of its points.
   */
  orbits(): { degree: number; points: TorusPoint[] }[] {
    const seen = new Set<string>()
    const out: { degree: number; points: TorusPoint[] }[] = []
    for (const P of this.points()) {
      const key = `${P.x},${P.y}`
      if (seen.has(key)) continue
      const orbit: TorusPoint[] = []
      let Q = P
      do {
        orbit.push(Q)
        seen.add(`${Q.x},${Q.y}`)
        Q = this.frobenius(Q)
      } while (Q.x !== P.x || Q.y !== P.y)
      this.degreeCache.set(key, orbit.length)
      out.push({ degree: orbit.length, points: orbit })
    }
    return out
  }

  /**
   * The cosets of the cyclic subgroup ⟨g⟩ — they partition the group into
   * size/order(g) classes, each listed in cyclic order (P, P+g, P+2g, …).
   * These are the cycles of the Cayley graph for a generating set containing g.
   */
  cosets(g: TorusPoint): TorusPoint[][] {
    const m = this.order(g)
    const seen = new Set<string>()
    const out: TorusPoint[][] = []
    for (const P of this.points()) {
      if (seen.has(`${P.x},${P.y}`)) continue
      const coset: TorusPoint[] = []
      let Q = P
      for (let i = 0; i < m; i++) {
        coset.push(Q)
        seen.add(`${Q.x},${Q.y}`)
        Q = this.add(Q, g)
      }
      out.push(coset)
    }
    return out
  }

  /** Every point, enumerated as i·g₁ + j·g₂ (deterministic order). */
  points(): TorusPoint[] {
    const out: TorusPoint[] = []
    const [g1, g2] = [this.generators[0], this.generators[1]]
    const [o1, o2] = [
      g1 ? this.order(g1) : 1,
      g2 ? this.order(g2) : 1,
    ]
    let P: TorusPoint = this.identity
    for (let i = 0; i < o1; i++) {
      let Q = P
      for (let j = 0; j < o2; j++) {
        out.push(Q)
        if (g2) Q = this.add(Q, g2)
      }
      if (g1) P = this.add(P, g1)
    }
    return out
  }

  /** (x + yτ)/N ∈ ℂ/Λ — floats begin HERE. */
  toComplex(P: TorusPoint): Complex {
    return new Complex(P.x / this.N + (P.y / this.N) * this.tau.re, (P.y / this.N) * this.tau.im)
  }
}
